/**
 * MIMI Agent - Builtin Skills Content
 * 
 * Auto-generated by build script or manually maintained to avoid filesystem reads in browser.
 */

export const BUILTIN_SKILLS_CONTENT: Record<string, string> = {
    'python_analysis': `---
name: python_analysis
description: "Executes Python code in a browser-based sandbox. Use this for data analysis, complex calculations, simulations, and visualizations."
capabilities: ["data-analysis", "python", "visualization", "calculation", "math"]
enabled: true
---

# INSTRUCTIONS

When the user asks for calculations, plots, or data processing:

1. **Write Python Code**: Enclose code in \`\`\`python ... \`\`\` blocks.
2. **Use Libraries**: \`numpy\`, \`pandas\`, \`matplotlib.pyplot\` are pre-installed.
3. **Visualize**: Use \`matplotlib\` to create charts. End with \`plt.show()\`.
4. **Be Direct**: Do not explain *how* to write the code unless asked. just write it.

## Example

User: "Plot a sine wave."

\`\`\`python
import numpy as np
import matplotlib.pyplot as plt

x = np.linspace(0, 10, 100)
y = np.sin(x)

plt.plot(x, y)
plt.title('Sine Wave')
plt.show()
\`\`\`
`,
    'sql_database': `---
name: sql_database
description: "Manages a local SQLite database in the browser. Use this to store structured data, run complex queries, and persist information."
capabilities: ["database", "sql", "storage", "structured-data"]
enabled: true
---

# INSTRUCTIONS

When the user asks to store data or query structured information:

1. **Write SQL**: Enclose code in \`\`\`sql ... \`\`\` blocks.
2. **Create Tables**: Always check if a table exists or create it first.
3. **Insert Data**: Populate the database with relevant data.
4. **Query**: Select data to show results.

## Example

User: "Create a user table and add John."

\`\`\`sql
CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY, name TEXT);
INSERT INTO users (name) VALUES ('John');
SELECT * FROM users;
\`\`\`
`,
    'research': `---
name: research
description: "Web-Recherche, Faktencheck und strukturierte Wissensaggregation."
capabilities: ["research", "web-search", "fact-check", "compare", "trends", "benchmark"]
enabled: true
---

# INSTRUCTIONS

When the user asks for research, comparisons, or fact-checking:

1. **Define the question** precisely and break into sub-questions.
2. **Search documents** using RAG if available.
3. **Structure results** in clear tables or summaries.
4. **Rate reliability** using ⭐ ratings.
5. **Provide recommendations** with reasoning.

## Output Format

| Aspekt | Ergebnis | Quelle | Zuverlässigkeit |
|--------|----------|--------|-----------------|
| ...    | ...      | ...    | ⭐⭐⭐⭐         |
`,
    'business_analysis': `---
name: business_analysis
description: "KPI-Berechnung, ROI-Analyse, SWOT, Budgetplanung und Geschäftsstrategien."
capabilities: ["business", "kpi", "roi", "finance", "strategy", "budget", "swot"]
enabled: true
---

# INSTRUCTIONS

When the user asks for business analysis, KPIs, or financial calculations:

1. **Identify KPIs** relevant to the question.
2. **Calculate** using Python with pandas.
3. **Visualize** results with matplotlib charts.
4. **Recommend** actions with priority levels.

## Example

\`\`\`python
import pandas as pd

kpis = pd.DataFrame({
    'KPI': ['Umsatz', 'Marge', 'Churn'],
    'Aktuell': [150000, 35, 5.2],
    'Ziel': [200000, 40, 3.0],
    'Einheit': ['€', '%', '%']
})
kpis['Erreichung'] = (kpis['Aktuell'] / kpis['Ziel'] * 100).round(1)
print(kpis.to_markdown(index=False))
\`\`\`
`,
    'security_audit': `---
name: security_audit
description: "Code-Sicherheitsaudit, DSGVO-Compliance und Schwachstellenanalyse."
capabilities: ["security", "audit", "vulnerability", "privacy", "gdpr", "encryption", "owasp"]
enabled: true
---

# INSTRUCTIONS

When the user asks about security, audits, or data privacy:

1. **Identify vulnerabilities** (OWASP Top 10).
2. **Rate severity**: 🔴 Kritisch | 🟠 Hoch | 🟡 Mittel | 🟢 Niedrig
3. **Suggest fixes** with concrete code examples.
4. **Check GDPR compliance** if applicable.

## Severity Table

| Severity | Anzahl | Beschreibung |
|----------|--------|-------------|
| 🔴 Kritisch | 0 | Sofort beheben |
| 🟠 Hoch | 0 | Diese Woche |
| 🟡 Mittel | 0 | Nächstes Sprint |
| 🟢 Niedrig | 0 | Bei Gelegenheit |
`,
    'translation': `---
name: translation
description: "Professionelle Übersetzungen, Lokalisierung und i18n-Dateien."
capabilities: ["translate", "localize", "i18n", "multilingual", "language"]
enabled: true
---

# INSTRUCTIONS

When the user asks for translations or localization:

1. **Detect source language** automatically.
2. **Translate contextually** (not literally).
3. **Preserve technical terms**.
4. **Format as table** for multiple languages.
5. **Generate i18n files** (JSON/TS) when requested.

## Output Format

| 🇩🇪 Deutsch | 🇺🇸 English | 🇫🇷 Français | 🇪🇸 Español |
|-------------|-------------|-------------|-------------|
| Benutzer    | User        | Utilisateur | Usuario     |
`,
    'ui_design': `---
name: ui_design
description: "UI/UX-Design, Farbschemata, Layout-Konzepte und CSS-Architektur."
capabilities: ["design", "ui", "ux", "color", "layout", "css", "animation", "responsive"]
enabled: true
---

# INSTRUCTIONS

When the user asks about design, UI, or styling:

1. **Propose modern designs** (glassmorphism, dark mode, gradients).
2. **Provide CSS/Tailwind code** directly.
3. **Define color palettes** with hex codes.
4. **Consider accessibility** (WCAG 2.1 AA).
5. **Mobile-first** approach.

## Design Tokens

\`\`\`css
:root {
  --bg-primary: #0a0a0f;
  --accent: #6366f1;
  --accent-gradient: linear-gradient(135deg, #6366f1, #8b5cf6);
  --glass: rgba(255, 255, 255, 0.05);
  --glass-border: rgba(255, 255, 255, 0.1);
}
\`\`\`
`
};
